config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  # root "home#index"
  root "friends#index"
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
     belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ] 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
require "uri"
require "net/http"
class HomeController < ApplicationController
  def index
  end
  
  def about
        uri = URI("https://icanhazdadjoke.com/")
        request= Net::HTTP::Get.new(uri, 'Content-Type' => 'application/json')
        p request
        @about_me=request
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
   <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="mb-3">
  <div>
    <%= form.label :first_name, style: "display: block", class:"form-label font-monospace" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>
</br>
  <div>
    <%= form.label :last_name, style: "display: block", class:"form-label font-monospace" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>
</br>
  <div>
    <%= form.label :email, style: "display: block", class:"form-label font-monospace" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>
</br>
  <div>
    <%= form.label :phone, style: "display: block", class:"form-label font-monospace" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>
</br>
  <div>
    <%= form.label :twitter, style: "display: block", class:"form-label font-monospace" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>
</br>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id , type: :hidden %>

</br>
  <div>
    <%= form.submit class:"btn btn-success font-monospace" %>
  </div>
<% end %>
</div>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

</br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-primary font-monospace" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary font-monospace" %>
</div>

app/views/friends/index.html.erb
<%if user_signed_in?%>
<div class="card">
<h5 class="card-header font-monospace">Friends</h5>
<div class="card-body">

<table class="table table-striped table-hover">
  <thead>
    <tr class="table-dark">
      <th class="font-monospace" scope="col">Name</th>
      <%# <th scope="col">Last name</th> %>
      <th class="font-monospace" scope="col">Email</th>
      <th class="font-monospace" scope="col">Phone</th>
      <th class="font-monospace" scope="col">Twitter</th>
      <th class="font-monospace" scope="col">Created By</th>
      <%if user_signed_in?%>
      <th class="font-monospace" colspan="2" scope="col"></th>
      <%end%>
    </tr>
  </thead>
  <tbody>
 <% @friends.each do |friend| %>
 <%if friend.user==current_user%>
    <tr>
      <td>
      <%= link_to friend.first_name+ " " + friend.last_name, friend %>
     
      <td class="font-monospace"><%= friend.email %></td>
      <td class="font-monospace"><%= friend.phone %></td>
      <td class="font-monospace"><%= friend.twitter %></td>
      <td class="font-monospace"><%= friend.user_id %></td>
      <%if friend.user == current_user  %>
      <td class="font-monospace"><%= link_to "Edit", edit_friend_path(friend), class:"btn btn-outline-warning" %></td>
      <td class="font-monospace"><%= button_to "Delete", friend, class:"btn btn-outline-danger", method: :delete %></td>
      <% elsif user_signed_in?%>
      <td class="font-monospace"></td>
      <td class="font-monospace"></td>
      <%end%>
    </tr>
     <% end %>
     <%end%>
  </tbody>
</table>
<%= link_to "Add a friend", new_friend_path, class:"btn btn-secondary font-monospace" %>

</div>
</div>
<%else%>

<h1>Hello world</h1>



<% end %>

app/views/friends/new.html.erb
<div class="card">
<h5 class="card-header font-monospace">New friend</h5>
<div class="card-body">
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-secondary font-monospace" %>
</div>

</div>

app/views/friends/show.html.erb
<div class="card" >
  <h5 class="card-header font-monospace">
    Friend
  </h5>
  <ul class="list-group list-group-flush font-monospace">
    <li class="list-group-item "><b>Name: </b><%=  @friend.first_name %> <%=  @friend.last_name %></li>
    <%# <li class="list-group-item"><b>Last name: </b></li> %>
    <li class="list-group-item"><b>Email: </b><%=  @friend.email %></li>
    <li class="list-group-item"><b>Phone: </b><%=  @friend.phone %></li>
    <li class="list-group-item"><b>Twitter: </b><%=  @friend.twitter %></li>
    <li class="list-group-item d-flex justify-content-around">
      <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-warning"%>
       <%= button_to "Delete", @friend, method: :delete, class:"btn btn-danger" %>    
     <%= link_to "Back", friends_path, class:"btn btn-secondary"%>
    </li>
   
      

  </ul>
</div>

app/views/home/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-secondary">
  <div class="container-fluid">
  <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="/">Friend App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-nav d-flex justify-content-between" id="navbarNav">
   
     <ul class="navbar-nav">
     <%if !user_signed_in?%>
       <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class:"nav-link"%>
        </li>
        </ul>
         <ul class="navbar-nav">
          <li class="nav-item">
        <%= link_to "Sign up",  new_user_registration_path, class:"nav-link btn btn-danger"%>
        </li>
         </ul>
          
                <%end%>
<%=link_to "About", home_about_path, class:"nav-link"%>

         <%if user_signed_in?%>
    
            <li class="nav-item">
        <%= link_to "New Friend", new_friend_path, class:"nav-link"%>
        </li>
         <li class="nav-item">
        <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link"%>
        </li>
        </ul>
          <li class="nav-item">
        <%= button_to "Sign out",  destroy_user_session_path, :method => :delete, class:"btn btn-warning"%>
        </li>
        <%end%>
     
        
        <%# <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> %>
     
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> <%=@about_me%> </h1>

app/views/home/index.html.erb
<h1>Hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render "home/header"%>
  <div class="container">
  <br/>
  <%if notice %>
  <%= render "home/alert"%>
  <%end%>
  <br/>
   <%= yield %>
  </div>
  </body>
</html>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>